### ISSUE TITLE
支持oracle吗

### ISSUE THREAD

**Issue by jaythc** [gyoomi/framework#1]
支持oracle吗

**Comment by gyoomi** [comment]
现阶段只支持MySql,，后面如果有需要的话会做Oracle相关方面的支持

**Comment by gyoomi** [comment]
> 支持oracle吗

目前移除原有的Jdbc逻辑，使用MyBatis-Plus。支持常见的数据库。如MySQL Oracle DB2 SQLServer

**Comment by gyoomi** [comment]
目前移除原有的Jdbc逻辑，使用MyBatis-Plus。支持常见的数据库。如MySQL Oracle DB2 SQLServer
